HRMS/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using ViewModel;
using Service;

namespace HRMS
{
  public class EmployeeController : BaseController
    {
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {

            MasterViewModel obj = new MasterViewModel();
            DesignationTypeService service = new Service.DesignationTypeService();
            EmployeeStatusService eservice = new EmployeeStatusService();

            obj.Designations = service.Get().ToList();
            obj.EmployeeStatus = eservice.Get().ToList();
            return View(obj);

        }
  }
}
      

HRMS/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using System.DirectoryServices.AccountManagement;
namespace HRMS
{
    public class UploadController : BaseController
    {
        /// <summary>
        /// Upload a file and return a JSON result
        /// </summary>
        /// <param name="file">The file to upload.</param>
        /// <returns>a FileUploadJsonResult</returns>
        /// <remarks>
        /// It is not possible to upload files using the browser's XMLHttpRequest
        /// object. So the jQuery Form Plugin uses a hidden iframe element. For a
        /// JSON response, a ContentType of application/json will cause bad browser
        /// behavior so the content-type must be text/html. Browsers can behave badly
        /// if you return JSON with ContentType of text/html. So you must surround
        /// the JSON in textarea tags. All this is handled nicely in the browser
        /// by the jQuery Form Plugin. But we need to overide the default behavior
        /// of the JsonResult class in order to achieve the desired result.
        /// </remarks>
        /// <seealso cref="http://malsup.com/jquery/form/#code-samples"/>
        /// 

        
        public FileUploadJsonResult AjaxUpload(HttpPostedFileBase file)
        {
            if (Request.Form["taskExcel"] == "true")
            {
                return ExcelUpload(file);
            }
            else
            {
                try
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        // extract only the fielname 
                        var fileName = System.IO.Path.GetFileName(file.FileName);

                        if (fileName.Contains("!") || fileName.Contains("@") || fileName.Contains("#") || fileName.Contains("$") || fileName.Contains("%") || fileName.Contains("^") || fileName.Contains("&") || fileName.Contains("*") || fileName.Contains("+"))
                        {
                            throw new Exception("The filename may not contain the following characters: !,@,#,$,%,^,&,*,+");
                        };

                        Random random = new Random(DateTime.Now.Second);
                        string path = "";
                        string rootPath = ConfigurationManager.AppSettings["RootUploadPath"];

                        path = Request.Form["uploadPath"];
                        string enforceName = Request.Form["enforceName"];

                        // System Throwing Strange Error, may be the beta, wrapping in try catch
                        try
                        {
                            System.IO.Directory.CreateDirectory(rootPath + path);
                        }
                        catch
                        {
                        }

                        try
                        {
                            System.IO.Directory.CreateDirectory(rootPath + path + "\\Archive");
                        }
                        catch
                        {
                        }


                        if (System.IO.File.Exists(rootPath + path + "\\" + fileName))
                        {
                            if (enforceName != null)
                            {
                                throw new Exception("File name already exists");
                            }
                            int randNum = random.Next();
                            for (int i = 0; i < 10000; i++)
                            {
                                if (!System.IO.File.Exists(rootPath + path + "\\Archive\\" + fileName.Split('.')[0] + randNum.ToString() + "." + fileName.Split('.')[1]))
                                {
                                    System.IO.File.Copy(rootPath + path + "\\" + fileName, rootPath + path + "\\Archive\\" + fileName.Split('.')[0] + randNum.ToString() + "." + fileName.Split('.')[1]);
                                    System.IO.File.Delete(rootPath + path + "\\" + fileName);
                                    break;
                                }
                            }
                        }

                        // store the file inside ~/App_Data/uploads folder 
                        var tempPath = System.IO.Path.Combine(rootPath + path, fileName);
                        file.SaveAs(tempPath);

                        // Return JSON
                        return new FileUploadJsonResult { Data = new { message = string.Format("{0} uploaded successfully.", System.IO.Path.GetFileName(file.FileName)), fileName = file.FileName } };
                    }

                    return null;
                }
                catch (Exception ex)
                {
                    return new FileUploadJsonResult { Data = new { message = string.Format("Uploading Error: {0}", ex.Message.ToString()) } };
                }
            }
        }

        public FileUploadJsonResult ExcelUpload(HttpPostedFileBase file)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    // extract only the fielname
                    DateTime dt = DateTime.Now;


                    var fileName = "Excel" + dt.Ticks.ToString() + ".xlsx";  //System.IO.Path.GetFileName(file.FileName);

                    string path = "";
                    string rootPath = "C:\\PivotDocuments\\";

                    if (Request.Form["uploadPath"] == String.Empty)
                    {
                        throw new Exception("No uploadPath variable specified in the upload form");
                    }
                    else
                    {
                        path = Request.Form["uploadPath"];
                    }

                    int projectId = 0;
                    if (Request.Form["uploadProjectId"] == String.Empty)
                    {
                        throw new Exception("No projectId available");
                    }
                    else
                    {
                        projectId = Convert.ToInt32(Request.Form["uploadProjectId"].ToString());
                    }

                    // store the file inside ~/App_Data/uploads folder 
                    var tempPath = System.IO.Path.Combine(rootPath + path, fileName);
                    file.SaveAs(tempPath);

                    //TaskService ts = new TaskService();
                    //ts.importExcel(tempPath, projectId);

                    // Return JSON
                    return new FileUploadJsonResult { Data = new { message = string.Format("{0} uploaded successfully.", fileName), fileName = fileName } };
                }

                return null;
            }
            catch (Exception ex)
            {
                return new FileUploadJsonResult { Data = new { message = string.Format("Uploading Error: {0}", ex.Message.ToString()) } };
            }
        }

        //public FileResult DownloadFile(int fileDocumentID)
        //{
        //    Service.EventDocumentReferenceService service = new Service.EventDocumentReferenceService();
        //    Model.EventDocumentReference doc = service.GetById(fileDocumentID);
        //    return File(doc.DocContent, "application/octet-stream", doc.FileName);

        //}
    }

    public class FileUploadJsonResult : JsonResult
    {
        public override void ExecuteResult(ControllerContext context)
        {
            this.ContentType = "text/html";
            context.HttpContext.Response.Write("<textarea>");
            base.ExecuteResult(context);
            context.HttpContext.Response.Write("</textarea>");
        }
    }
}

HRMS/Views/Controls/DocumentTypeDetailsView.cshtml
@model ViewModel.MasterViewModel
@using Model

<div id="documentTypeDetailsWindow" class="detailsWindow">

    <form id="documentTypeDetailsForm"
          name="documentTypeDetailsForm"
          data-ui-binding="true"
          data-service-object="documentTypeService"
          data-associated-list="documentTypeGrid"
          method="get" action="" class="form-horizontal" role="form">

        <div class="modal-body container-fluid">

            <div id="documentTypeErrorDisplay" class="documentTypeErrorDisplay" data-error-display="true"></div>

            <fieldset>
                <legend>General Information</legend>

                <div class="form-group">
                    <input type="hidden" ng-model="model.DocumentTypeID" />
                </div>

                <div class="form-group">

                    <label class="col-sm-2 alignlbls">Description <i class="lblRequired">*</i></label>          
                    <div class="col-sm-4">
                        <input type="text" name="em_Description" id="em_Description" ng-model="model.Description" class="required form-control" maxlength="500" />
                    </div>                
                </div>
            </fieldset>
        </div>

        <div class="modal-footer">
            <div class="editor-label">
                <button class="btn btn-primary btn-sm">Save</button>
                <button type="button" class="btn btn-primary btn-sm" ng-click="fb.HideForm(true)">Cancel</button>
            </div>
        </div>
    </form>
</div>

HRMS/Views/Controls/DocumentTypeListView.cshtml
@model ViewModel.MasterViewModel
@using Model

<div id="documentTypeListView" class="listView">
    <style>
        .actioncell {
            width: 20%;
        }

        .normalcell {
            width: 60%;
        }
    </style>

    @*<form class="form-inline">

        </form>*@
    @*<div class="form-group mt-md"></div>*@
    <table id="documentTypeGrid"
           data-ui-binding="true"
           data-entity-key="DocumentTypeID"
           data-service-object="documentTypeService"
           data-default-orderby="Description"
           class="table table-condensed table-hover"
           data-page-size="10">
        <thead class="tblaction">
            <tr>
                <td colspan="3">
                    <table class="col-md-5">
                        <tr>
                            <td class="col-md-4">
                                <input type="text" class="form-control"
                                       data-search-fields="Description"
                                       data-search-list="documentTypeGrid"
                                       data-default-focus="true" />
                            </td>
                            <td class="col-md-4"><button type="button" class="btn btn-primary" ng-click="ub.NewForm('documentTypeDetailsForm', true, null)">New Document Type</button></td>
                        </tr>
                    </table>                   
                </td>
            </tr>
        </thead>
        <tr>
            @*<th><a href="#" data-sort-field="DocumentTypeID">Document Type ID</a></th>*@
            <th class="normalcell"><a href="#" data-sort-field="Description">Description</a></th>
            <th class="actioncell">Edit</th>
            <th class="actioncell">Delete</th>
        </tr>
        <tbody ng-repeat="r in rows">
            <tr alt=$index%2>
                @*<td class="col-md-1"> <span>{{r.DocumentTypeID}}</span></td>*@
                <td class="col-md-1"> <span>{{r.Description}}</span></td>
                <td class="col-md-1"><img src="~/Content/images/edit.png" alt="Edit" title="Edit" width="20" ng-click="ub.LoadForm('documentTypeDetailsForm',  r.DocumentTypeID , true, null)" /></td>
                <td class="col-md-1"><img src="~/Content/images/delete.png" alt="Delete" title="Delete" width="20" ng-click="lb.Delete(r.DocumentTypeID, 'Are you sure you want to delete this Document Type?' , ub.documentTypeDeleteCallback)" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" align="center">
                    <div id="documentTypePagination">
                        <span>{{pageText}}</span>&nbsp;&nbsp;
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageFirst()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><<</span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PagePrevious()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><</span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageNext()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>></span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageLast()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>>></span></button>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

HRMS/Views/Controls/EmployeeStatusHistoryEditView.cshtml
@model ViewModel.MasterViewModel
@using Model



<div id="EmployeeStatusHistoryEditWindow" class="detailsWindow">

    <form id="EmployeeStatusHistoryForm"
          name="EmployeeStatusHistoryForm"
          data-ui-binding="true"
          data-service-object="employeeStatusHistoryService"
          data-associated-list="employeeStatusHistoryGrid"
          method="get" action="" class="form-horizontal" role="form">

        <div class="modal-body">

            <div id="EmployeeStatusErrorDisplay" class="EmployeeStatusErrorDisplay" data-error-display="true"></div>

            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="form-group">
                        <input type="hidden" ng-model="model.EmployeeStatusID" />

                        <label for="empcode">Employee Status</label><br />
                        <spam>{{model.EmployeeStatu.Status}}</spam>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-md-3">
                    <div class="form-group">
                        <label for="em_StartDateDetails">Start Date</label>
                        <input type="text" name="em_StartDateDetails" id="em_StartDateDetails" ng-model="model.StartDate" class="form-control date-width" date-Picker />
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="form-group">
                        <label for="em_EndDateDetails">End Date</label>
                        <input type="text" name="em_EndDateDetails" id="em_EndDateDetails" ng-model="model.EndDate" class="form-control date-width" date-Picker />
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="form-group">
                        <label for="statusNote">Note</label>
                        <textarea name="Note" style="height:100px;width:170px;" id="statusNote" ng-model="model.StatusNote" class="form-control"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <div class="editor-label">
                <button class="btn btn-primary btn-sm">Save</button>
                <button type="button" class="btn btn-primary btn-sm" ng-click="fb.HideForm(true)">Cancel</button>
            </div>
        </div>
    </form>
</div>

HRMS/Views/Controls/EmployeeStatusHistoryListView.cshtml
@model ViewModel.MasterViewModel
@using Model

<div id="EmployeeStatusHistoryListView" class="listView">
    
    <h3 class="title"> <span>@ViewBag.FullName's Status</span> </h3>  
    <select id="employeeStatusFilter" data-filter-list="employeeStatusHistoryGrid" style="display:none" data-filter-field="EmployeeID">
        <option value="@ViewBag.EmployeeID">@ViewBag.EmployeeID</option>
    </select>

    <table id="employeeStatusHistoryGrid"
           data-ui-binding="true"
           data-entity-key="EmployeeStatusID"
           data-service-object="employeeStatusHistoryService"
           data-default-orderby="EmployeeStatusID"
           class="table table-condensed table-hover"
           data-page-size="10">
        <thead>
            <tr><td>
                    <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#StatusDialog" ng-click="ub.loadFormEmployeeStatusHistory('employeeStatusHistoryDetailsForm',rows[0].EmployeeID, false)">
                        Change Status
                    </button>
                    <button type="button" id="btnCancel" class="btn btn-primary btn-sm" onclick="@("window.location.href='" + @Url.Action("Index", "Employee") + "'");">Back</button>
                </td></tr>
        </thead>
        <tr>
            <th><a href="#" data-sort-field="EmployeeStatus">Employee Status</a></th>
            <th><a href="#" data-sort-field="StartDate">Start Date</a></th>
            <th><a href="#" data-sort-field="EndDate">End Date</a></th>
            <th><a href="#" data-sort-field="StatusNote">Status Note</a></th>
            <th class="text-center">Edit</th>
        </tr>
        <tbody ng-repeat="r in rows">
            <tr alt=$index%2>
                <td class="col-md-1"> <span>{{r.EmployeeStatus.Status}}</span></td>
                <td class="col-md-1"> <span>{{r.StartDate | date:'dd/MM/yyyy'}}</span></td>
                <td class="col-md-1"> <span>{{r.EndDate | date:'dd/MM/yyyy'}}</span></td>
                <td class="col-md-1"> <span>{{r.StatusNote}}</span></td>
                <td class="col-md-1 text-center">
                    <a href='javascript:;' ng-click="ub.LoadForm('EmployeeStatusHistoryForm',r.EmployeeStatusID , true, null)">
                        <img src="~/Content/images/edit.png" alt="Edit" title="Edit" width="20" />
                    </a>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" align="center">
                    <div id="EmployeeStatusPagination">
                        <span>{{pageText}}</span>&nbsp;&nbsp;
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageFirst()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><<</span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PagePrevious()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><</span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageNext()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>></span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageLast()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>>></span></button>  
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

HRMS/Views/Controls/EmployeeStatusListView.cshtml
@model ViewModel.MasterViewModel
@using Model

<div id="EmployeeStatusListView" class="listView">

    <table id="EmployeeStatusGrid"
           data-ui-binding="true"
           data-entity-key="EmployeeStatusID"
           data-service-object="EmployeeStatusService"
           data-default-orderby="StatusID"
           class="table table-condensed table-hover"
           data-page-size="10">
        <thead class="tblaction">
            <tr>
                <td colspan="4">
                    <table class="col-md-5">
                        <tr>
                            <td class="col-md-4">
                                <input type="text" class="form-control"
                                       data-search-fields="Status, Description"
                                       data-search-list="EmployeeStatusGrid"
                                       data-default-focus="true" />
                            </td>
                            <td class="col-md-4"><button type="button" class="btn" ng-click="ub.NewForm('EmployeeStatusDetailsForm', true, null)">New Status Type</button></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </thead>
        <tr>
            <th><a href="#" data-sort-field="StatusID">Status Type ID</a></th>
            <th><a href="#" data-sort-field="Status">Status</a></th>
            <th><a href="#" data-sort-field="Description">Description</a></th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <tbody ng-repeat="r in rows">
            <tr alt=$index%2>
                <td class="col-md-1"> <span>{{r.StatusID}}</span></td>
                <td class="col-md-1"> <span>{{r.Status}}</span></td>
                <td class="col-md-1"> <span>{{r.Description}}</span></td>
                <td class="col-md-1"><img src="~/Content/images/edit.png" alt="edit" title="Edit" width="20" ng-click="ub.LoadForm('EmployeeStatusDetailsForm',  r.StatusID , true, null)" /></td>
                <td class="col-md-1"><img src="~/Content/images/delete.png" alt="delete" title="Delete" width="20" ng-click="lb.Delete(r.StatusID, 'Are you sure you want to delete this Status?' , ub.EmployeeStatusDeleteCallback)" /></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" align="center">
                    <div id="EmployeeStatusPagination">
                        <span>{{pageText}}</span>&nbsp;&nbsp;
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageFirst()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><<</span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PagePrevious()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><</span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageNext()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>></span></button>
                        <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageLast()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>>></span></button>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

HRMS/Views/Controls/ITDeclarationListView.cshtml
    @model ViewModel.MasterViewModel
@using Model

<div class="listView" id="itDeclarationListView">
    <div class="middlewrap">



        <div class="table-responsive tbl-scroll">
            <h3 class="title"> <span>IT Declaration for @ViewBag.Name</span> </h3>
            @*<input type="hidden" id="hdnEmployeeID" value="@ViewBag.EmployeeID" />
            <input type="hidden" id="hdnPan" value="@ViewBag.Pan" />

            <input type="hidden" id="hdnAddressLine1" value="@ViewBag.AddressLine1" />
            <input type="hidden" id="hdnAddressLine2" value="@ViewBag.AddressLine2" />
            <input type="hidden" id="hdnAddressLine3" value="@ViewBag.AddressLine3" />
            <input type="hidden" id="hdnAddressCity" value="@ViewBag.AddressCity" />
            <input type="hidden" id="hdnAddressState" value="@ViewBag.AddressState" />
            <input type="hidden" id="hdnAddressZip" value="@ViewBag.AddressZip" />
            <input type="hidden" id="hdnAddressCountry" value="@ViewBag.AddressCountry" />

            <input type="hidden" id="hdnMobileNumber" value="@ViewBag.MobileNumber" />*@

            <table class="table table-condensed table-hover"
                   id="itDeclarationGrid"
                   data-ui-binding="true"
                   data-entity-key="ItDeclarationID"
                   data-service-object="itDeclarationService"
                   data-default-orderby="ItDeclarationYear"
                   cellspacing="0" cellpadding="0" border="0"
                   data-page-size="10">
                <thead class="tblaction">
                    <tr>
                        <td colspan="6">
                            <table class="col-md-5">
                                <tr>
                                    <td class="col-md-3">
                                        <select id="yearFilter" data-filter-list="itDeclarationGrid" data-filter-field="ItDeclarationYear" class="form-control">
                                            <option value="">Select Financial Year</option>
                                            @foreach (var year in Model.Years)
                                            {
                                                <option value="@year">@year - @(year + 1)</option>
                                            }
                                        </select>
                                    </td>
                                    <td class="col-md-2">
                                        <button type="button" ng-click="ub.NewItDeclarationDetailForm('itDeclarationDetailsForm',true,'')" class="btn btn-primary">Add New</button>
                                        <button type="button" id="btnBack" class="btn btn-primary" onclick="@(" window.location.href='" + @Url.Action("Index", "Employee") + "' ");">Back</button>
                                    </td>
                                </tr>
                            </table>
                            <div class="form-group m-0">
                                <select id="statusFilter" data-filter-list="itDeclarationGrid" data-filter-field="EmployeeID" style="display:none">
                                    <option value="@ViewBag.EmployeeID">@ViewBag.EmployeeID</option>
                                </select>
                            </div>
                        </td>
                    </tr>
                </thead>

                <thead>
                    <tr>

                        <th class="text-left">Year</th>
                        <th class="text-left">Name</th>
                        <th class="text-left">PAN Number</th>
                        <th class="text-left">Date</th>
                        <th class="text-left">Edit</th>
                        <th class="text-left">Delete</th>
                    </tr>
                </thead>
                <tbody>

                    <tr alt=$index%2 ng-repeat="r in rows">

                        <td class="text-left">{{r.ItDeclarationYear}} -{{r.ItDeclarationYear+1}}</td>
                        <td class="text-left">@ViewBag.Name</td>
                        <td class="text-left">{{r.PanNo}}</td>
                        <td class="text-left">{{r.Date  | date:'dd/MM/yyyy'}}</td>
                        <td class="text-left">
                            <a href='javascript:;' ng-click="ub.loadITDeclarationForm('itDeclarationDetailsForm',  r.ItDeclarationID , true)">
                                <img src="~/Content/images/edit.png" alt="Edit" title="Edit" width="20" />
                            </a>
                        </td>
                        <td class="text-left">
                            <a href='javascript:;' ng-click="lb.Delete(r.ItDeclarationID, 'Are you sure you want to delete this IT Declaration?' , ub.itDeclarationDeleteCallback)">
                                <img src="~/Content/images/delete.png" alt="Delete" title="Delete" width="20" />
                            </a>
                        </td>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6" align="center">
                            <div id="monthPagination">
                                <span>{{pageText}}</span>&nbsp;&nbsp;
                                <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageFirst()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><<</span></button>
                                <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PagePrevious()" ng-disabled="TotalRows <= pageSize || pageIndex==0"><span><</span></button>
                                <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageNext()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>></span></button>
                                <button type="button" class="btn btn-primary btn-sm" ng-click="lb.PageLast()" ng-disabled="TotalRows <= pageSize || totalPages==pageIndex+1"><span>>></span></button>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

    </div>
</div>

HRMS/Views/Controls/UploadControl.cshtml
@model ViewModel.MasterViewModel
@using Model;

<div id="fileUploadPopUp" class="modal fade" role="dialog" aria-hidden="true">

    <form id="ajaxUploadForm" action="@Url.Action("AjaxUpload", "Upload")" method="post" enctype="multipart/form-data">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4> Upload a file</h4>
                </div>
                <div class="modal-body">
                    <fieldset>
                        <label>File to Upload: <i class="lblRequired">*</i> <input type="file"  name="file" id="fileUpload" class="required" />(10MB max size)</label>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <input id="ajaxUploadButton" type="submit"
                           onclick="if ($('#fileUpload').val() == '') { toastr.error('Please select file to upload'); return false; } if (document.getElementById('fileUpload').files[0].size > 10000000) { toastr.error('Please select a file of maximum size upto 10MB'); return false; }" value="Submit" class="btn btn-general" />
                    <input id="uploadPath" name="uploadPath" type="hidden" value="" />
                    <button type="button" class="btn btn-bordered" data-dismiss="modal">Cancel</button>
                    
                </div>
            </div>
        </div>
    </form>
</div>